-record(chain, {prefix="", suffix=""}).
-record(suffix, {word="", count=0}).
-record(reducedChain, {prefix="", suffixes=[]}).
-record(dbInfo, {host="", user="", pass="", db=""}).
-record(dbPid, {pid=""}).
